;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-indent-line-or-region
        cperl-electric-brace
        cperl-electric-lbrace
        cperl-electric-paren
        cperl-electric-rparen
        cperl-electric-semi
        cperl-indent-command
        delete-indentation
        downcase-region
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        eval-last-sexp
        indent-for-tab-command
        kill-region
        markdown-outdent-or-delete
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        my/cycle-spacing
        phi-search
        phi-search-backward
        skeleton-pair-insert-maybe
        yaml-electric-dash-and-dot
        yank-rectangle
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        ido-switch-buffer
        scroll-other-window
        smex
        suspend-frame
        yas-expand
        ))
