;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cperl-electric-lbrace
        delete-indentation
        kill-region
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        phi-search
        phi-search-backward
        yank-rectangle
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        scroll-other-window
        smex
        yas-expand
        ))
